services:
    discordbot:
        build: .
        container_name: discordbot
        restart: unless-stopped
        volumes:
            # Important for persistence
            - /path/to/store/database:/bot/database
            # Optional but recommended
            - /path/to/store/logs:/bot/logs
        environment:
            - TOKEN=${TOKEN}
            - CLIENT_ID=${CLIENT_ID}
            - GUILD_ID=${GUILD_ID}
            - ACTIVITY=${ACTIVITY}
            - STATUS=${STATUS}
            - OWNERID=${OWNERID}
            - TZ=${TZ}
