version: '3'
services:
  thanujica:
    container_name: discordbot
    image: discordbot
    restart: unless-stopped
    environment:
      - TOKEN=your bot token
      - CLIENT_ID=your client id
      - GUILD_ID=optional if you want custom commands
      - ACTIVITY=ONLINE, DND, INVISIBLE, etc
      - STATUS=The thing you want your bot to be playing
      - OWNERID=Your Discord ID goes here
