version: '3'
services:
  thanujica:
    container_name: discordbot
    image: iotashine/discordbot
    restart: unless-stopped
    volumes:
      - /home/iota/bot:/bot/database
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - ACTIVITY=${ACTIVITY}
      - STATUS=${STATUS}
      - OWNERID=${OWNERID}
